#!/usr/bin/env node

console.log('🚀 GUIDE DE DÉPLOIEMENT RAILWAY')
console.log('')
console.log('📋 ÉTAPES DE DÉPLOIEMENT :')
console.log('')
console.log('1️⃣ PRÉPARATION :')
console.log('   ✅ Fichiers de configuration créés')
console.log('   ✅ railway.toml configuré')
console.log('   ✅ Dockerfile optimisé')
console.log('   ✅ Scripts de build mis à jour')
console.log('   ✅ Health check endpoint ajouté')
console.log('')
console.log('2️⃣ INSTALLATION RAILWAY CLI :')
console.log('   npm install -g @railway/cli')
console.log('   # ou')
console.log('   curl -fsSL https://railway.app/install.sh | sh')
console.log('')
console.log('3️⃣ CONNEXION À RAILWAY :')
console.log('   railway login')
console.log('   # Suivez les instructions pour vous connecter')
console.log('')
console.log('4️⃣ INITIALISATION DU PROJET :')
console.log('   railway init')
console.log('   # Choisissez "Create new project"')
console.log('   # Donnez un nom à votre projet (ex: alami-gestion)')
console.log('')
console.log('5️⃣ AJOUT DE LA BASE DE DONNÉES :')
console.log('   railway add postgresql')
console.log('   # Cela créera automatiquement une base PostgreSQL')
console.log('')
console.log('6️⃣ CONFIGURATION DES VARIABLES D\'ENVIRONNEMENT :')
console.log('   railway variables set JWT_SECRET="votre-secret-jwt-super-securise"')
console.log('   railway variables set NODE_ENV="production"')
console.log('   railway variables set NEXT_PUBLIC_APP_URL="https://votre-app.railway.app"')
console.log('')
console.log('   # La DATABASE_URL sera automatiquement configurée par Railway')
console.log('')
console.log('7️⃣ DÉPLOIEMENT :')
console.log('   railway up')
console.log('   # Ou pour déployer depuis GitHub :')
console.log('   # Connectez votre repo GitHub dans le dashboard Railway')
console.log('')
console.log('8️⃣ MIGRATION DE LA BASE DE DONNÉES :')
console.log('   railway run prisma migrate deploy')
console.log('   # Ou si vous préférez push :')
console.log('   railway run prisma db push')
console.log('')
console.log('9️⃣ CRÉATION D\'UN UTILISATEUR ADMIN :')
console.log('   railway run node scripts/create-owner.js')
console.log('')
console.log('🔟 VÉRIFICATION :')
console.log('   # Votre app sera disponible sur :')
console.log('   # https://votre-projet.railway.app')
console.log('')
console.log('📊 COMMANDES UTILES :')
console.log('')
console.log('   🔍 Voir les logs :')
console.log('   railway logs')
console.log('')
console.log('   🔧 Ouvrir le shell :')
console.log('   railway shell')
console.log('')
console.log('   📱 Ouvrir l\'app :')
console.log('   railway open')
console.log('')
console.log('   ⚙️ Variables d\'environnement :')
console.log('   railway variables')
console.log('')
console.log('   🗄️ Connexion à la DB :')
console.log('   railway connect postgresql')
console.log('')
console.log('🔒 VARIABLES D\'ENVIRONNEMENT REQUISES :')
console.log('')
console.log('   DATABASE_URL     → Automatique (Railway PostgreSQL)')
console.log('   JWT_SECRET       → À définir (chaîne sécurisée)')
console.log('   NODE_ENV         → production')
console.log('   NEXT_PUBLIC_APP_URL → URL de votre app Railway')
console.log('')
console.log('💡 CONSEILS :')
console.log('')
console.log('   🔐 Sécurité :')
console.log('   • Utilisez un JWT_SECRET fort (32+ caractères)')
console.log('   • Ne commitez jamais les variables sensibles')
console.log('   • Activez l\'authentification 2FA sur Railway')
console.log('')
console.log('   📈 Performance :')
console.log('   • Railway utilise Nixpacks par défaut')
console.log('   • Le build inclut automatiquement Prisma generate')
console.log('   • Les migrations sont exécutées au déploiement')
console.log('')
console.log('   🔄 CI/CD :')
console.log('   • Connectez votre repo GitHub pour auto-deploy')
console.log('   • Les push sur main déclenchent un redéploiement')
console.log('   • Utilisez les environments pour staging/prod')
console.log('')
console.log('🚨 DÉPANNAGE :')
console.log('')
console.log('   ❌ Erreur de build :')
console.log('   • Vérifiez que toutes les dépendances sont dans package.json')
console.log('   • Assurez-vous que Prisma generate s\'exécute')
console.log('')
console.log('   ❌ Erreur de DB :')
console.log('   • Vérifiez que les migrations sont appliquées')
console.log('   • Utilisez railway logs pour voir les erreurs')
console.log('')
console.log('   ❌ Erreur 503 :')
console.log('   • Vérifiez le health check : /api/health')
console.log('   • Augmentez le timeout si nécessaire')
console.log('')
console.log('🎯 ÉTAPES SUIVANTES APRÈS DÉPLOIEMENT :')
console.log('')
console.log('   1. Testez toutes les fonctionnalités')
console.log('   2. Créez un compte admin')
console.log('   3. Ajoutez des données de test')
console.log('   4. Configurez un nom de domaine personnalisé')
console.log('   5. Activez les sauvegardes automatiques')
console.log('')
console.log('🔗 LIENS UTILES :')
console.log('')
console.log('   📚 Documentation Railway : https://docs.railway.app')
console.log('   🎯 Dashboard Railway : https://railway.app/dashboard')
console.log('   💬 Support Railway : https://help.railway.app')
console.log('')
console.log('✨ VOTRE APPLICATION EST PRÊTE POUR LE DÉPLOIEMENT !')
console.log('🚀 Suivez les étapes ci-dessus pour déployer sur Railway !')
console.log('')
console.log('💡 Besoin d\'aide ? Consultez la documentation Railway ou contactez le support.')
